services:
  mlndownloder:
    image: mel0nabc/mlndownloader:latest
    container_name: mlndownloader
    ports:
      - "3000:8080"
    volumes:
      - ./downloads:/downloads
    environment: # To save files with this user and group
      - PUID=1000
      - PGID=1000
